// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/energy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Single prediction request
type PredictionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuModel        string                 `protobuf:"bytes,1,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	RamCapacityGb   float64                `protobuf:"fixed64,2,opt,name=ram_capacity_gb,json=ramCapacityGb,proto3" json:"ram_capacity_gb,omitempty"`
	CpuFreqMhz      int32                  `protobuf:"varint,3,opt,name=cpu_freq_mhz,json=cpuFreqMhz,proto3" json:"cpu_freq_mhz,omitempty"`
	NumCores        int32                  `protobuf:"varint,4,opt,name=num_cores,json=numCores,proto3" json:"num_cores,omitempty"`
	AchievedLoadPct float64                `protobuf:"fixed64,5,opt,name=achieved_load_pct,json=achievedLoadPct,proto3" json:"achieved_load_pct,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PredictionRequest) Reset() {
	*x = PredictionRequest{}
	mi := &file_proto_energy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionRequest) ProtoMessage() {}

func (x *PredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_energy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionRequest.ProtoReflect.Descriptor instead.
func (*PredictionRequest) Descriptor() ([]byte, []int) {
	return file_proto_energy_proto_rawDescGZIP(), []int{0}
}

func (x *PredictionRequest) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *PredictionRequest) GetRamCapacityGb() float64 {
	if x != nil {
		return x.RamCapacityGb
	}
	return 0
}

func (x *PredictionRequest) GetCpuFreqMhz() int32 {
	if x != nil {
		return x.CpuFreqMhz
	}
	return 0
}

func (x *PredictionRequest) GetNumCores() int32 {
	if x != nil {
		return x.NumCores
	}
	return 0
}

func (x *PredictionRequest) GetAchievedLoadPct() float64 {
	if x != nil {
		return x.AchievedLoadPct
	}
	return 0
}

// Response for a single prediction
type PredictionResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PredictedPowerWatts float64                `protobuf:"fixed64,1,opt,name=predicted_power_watts,json=predictedPowerWatts,proto3" json:"predicted_power_watts,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error               string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PredictionResponse) Reset() {
	*x = PredictionResponse{}
	mi := &file_proto_energy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictionResponse) ProtoMessage() {}

func (x *PredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_energy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictionResponse.ProtoReflect.Descriptor instead.
func (*PredictionResponse) Descriptor() ([]byte, []int) {
	return file_proto_energy_proto_rawDescGZIP(), []int{1}
}

func (x *PredictionResponse) GetPredictedPowerWatts() float64 {
	if x != nil {
		return x.PredictedPowerWatts
	}
	return 0
}

func (x *PredictionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PredictionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Batch prediction request
type BatchPredictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*PredictionRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictionRequest) Reset() {
	*x = BatchPredictionRequest{}
	mi := &file_proto_energy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictionRequest) ProtoMessage() {}

func (x *BatchPredictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_energy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictionRequest.ProtoReflect.Descriptor instead.
func (*BatchPredictionRequest) Descriptor() ([]byte, []int) {
	return file_proto_energy_proto_rawDescGZIP(), []int{2}
}

func (x *BatchPredictionRequest) GetRequests() []*PredictionRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// Response for batch prediction
type BatchPredictionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []float64              `protobuf:"fixed64,1,rep,packed,name=predictions,proto3" json:"predictions,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictionResponse) Reset() {
	*x = BatchPredictionResponse{}
	mi := &file_proto_energy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictionResponse) ProtoMessage() {}

func (x *BatchPredictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_energy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictionResponse.ProtoReflect.Descriptor instead.
func (*BatchPredictionResponse) Descriptor() ([]byte, []int) {
	return file_proto_energy_proto_rawDescGZIP(), []int{3}
}

func (x *BatchPredictionResponse) GetPredictions() []float64 {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *BatchPredictionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BatchPredictionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_energy_proto protoreflect.FileDescriptor

const file_proto_energy_proto_rawDesc = "" +
	"\n" +
	"\x12proto/energy.proto\x12\x06energy\"\xc3\x01\n" +
	"\x11PredictionRequest\x12\x1b\n" +
	"\tcpu_model\x18\x01 \x01(\tR\bcpuModel\x12&\n" +
	"\x0fram_capacity_gb\x18\x02 \x01(\x01R\rramCapacityGb\x12 \n" +
	"\fcpu_freq_mhz\x18\x03 \x01(\x05R\n" +
	"cpuFreqMhz\x12\x1b\n" +
	"\tnum_cores\x18\x04 \x01(\x05R\bnumCores\x12*\n" +
	"\x11achieved_load_pct\x18\x05 \x01(\x01R\x0fachievedLoadPct\"v\n" +
	"\x12PredictionResponse\x122\n" +
	"\x15predicted_power_watts\x18\x01 \x01(\x01R\x13predictedPowerWatts\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"O\n" +
	"\x16BatchPredictionRequest\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.energy.PredictionRequestR\brequests\"i\n" +
	"\x17BatchPredictionResponse\x12 \n" +
	"\vpredictions\x18\x01 \x03(\x01R\vpredictions\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xb0\x01\n" +
	"\rEnergyService\x12G\n" +
	"\fPredictPower\x12\x19.energy.PredictionRequest\x1a\x1a.energy.PredictionResponse\"\x00\x12V\n" +
	"\x11PredictPowerBatch\x12\x1e.energy.BatchPredictionRequest\x1a\x1f.energy.BatchPredictionResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_energy_proto_rawDescOnce sync.Once
	file_proto_energy_proto_rawDescData []byte
)

func file_proto_energy_proto_rawDescGZIP() []byte {
	file_proto_energy_proto_rawDescOnce.Do(func() {
		file_proto_energy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_energy_proto_rawDesc), len(file_proto_energy_proto_rawDesc)))
	})
	return file_proto_energy_proto_rawDescData
}

var file_proto_energy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_energy_proto_goTypes = []any{
	(*PredictionRequest)(nil),       // 0: energy.PredictionRequest
	(*PredictionResponse)(nil),      // 1: energy.PredictionResponse
	(*BatchPredictionRequest)(nil),  // 2: energy.BatchPredictionRequest
	(*BatchPredictionResponse)(nil), // 3: energy.BatchPredictionResponse
}
var file_proto_energy_proto_depIdxs = []int32{
	0, // 0: energy.BatchPredictionRequest.requests:type_name -> energy.PredictionRequest
	0, // 1: energy.EnergyService.PredictPower:input_type -> energy.PredictionRequest
	2, // 2: energy.EnergyService.PredictPowerBatch:input_type -> energy.BatchPredictionRequest
	1, // 3: energy.EnergyService.PredictPower:output_type -> energy.PredictionResponse
	3, // 4: energy.EnergyService.PredictPowerBatch:output_type -> energy.BatchPredictionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_energy_proto_init() }
func file_proto_energy_proto_init() {
	if File_proto_energy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_energy_proto_rawDesc), len(file_proto_energy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_energy_proto_goTypes,
		DependencyIndexes: file_proto_energy_proto_depIdxs,
		MessageInfos:      file_proto_energy_proto_msgTypes,
	}.Build()
	File_proto_energy_proto = out.File
	file_proto_energy_proto_goTypes = nil
	file_proto_energy_proto_depIdxs = nil
}
