# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: energy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'energy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65nergy.proto\x12\x06\x65nergy\"\x83\x01\n\x11PredictionRequest\x12\x11\n\tcpu_model\x18\x01 \x01(\t\x12\x17\n\x0fram_capacity_gb\x18\x02 \x01(\x01\x12\x14\n\x0c\x63pu_freq_mhz\x18\x03 \x01(\x05\x12\x11\n\tnum_cores\x18\x04 \x01(\x05\x12\x19\n\x11\x61\x63hieved_load_pct\x18\x05 \x01(\x01\"R\n\x12PredictionResponse\x12\x1d\n\x15predicted_power_watts\x18\x01 \x01(\x01\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"E\n\x16\x42\x61tchPredictionRequest\x12+\n\x08requests\x18\x01 \x03(\x0b\x32\x19.energy.PredictionRequest\"M\n\x17\x42\x61tchPredictionResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x01\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xb0\x01\n\rEnergyService\x12G\n\x0cPredictPower\x12\x19.energy.PredictionRequest\x1a\x1a.energy.PredictionResponse\"\x00\x12V\n\x11PredictPowerBatch\x12\x1e.energy.BatchPredictionRequest\x1a\x1f.energy.BatchPredictionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'energy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=25
  _globals['_PREDICTIONREQUEST']._serialized_end=156
  _globals['_PREDICTIONRESPONSE']._serialized_start=158
  _globals['_PREDICTIONRESPONSE']._serialized_end=240
  _globals['_BATCHPREDICTIONREQUEST']._serialized_start=242
  _globals['_BATCHPREDICTIONREQUEST']._serialized_end=311
  _globals['_BATCHPREDICTIONRESPONSE']._serialized_start=313
  _globals['_BATCHPREDICTIONRESPONSE']._serialized_end=390
  _globals['_ENERGYSERVICE']._serialized_start=393
  _globals['_ENERGYSERVICE']._serialized_end=569
# @@protoc_insertion_point(module_scope)
