# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import energy_pb2 as energy__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in energy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EnergyServiceStub(object):
    """Service definition for power prediction
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictPower = channel.unary_unary(
                '/energy.EnergyService/PredictPower',
                request_serializer=energy__pb2.PredictionRequest.SerializeToString,
                response_deserializer=energy__pb2.PredictionResponse.FromString,
                _registered_method=True)
        self.PredictPowerBatch = channel.unary_unary(
                '/energy.EnergyService/PredictPowerBatch',
                request_serializer=energy__pb2.BatchPredictionRequest.SerializeToString,
                response_deserializer=energy__pb2.BatchPredictionResponse.FromString,
                _registered_method=True)


class EnergyServiceServicer(object):
    """Service definition for power prediction
    """

    def PredictPower(self, request, context):
        """Predict power for a single request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictPowerBatch(self, request, context):
        """Predict power for multiple requests in batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnergyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictPower': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPower,
                    request_deserializer=energy__pb2.PredictionRequest.FromString,
                    response_serializer=energy__pb2.PredictionResponse.SerializeToString,
            ),
            'PredictPowerBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPowerBatch,
                    request_deserializer=energy__pb2.BatchPredictionRequest.FromString,
                    response_serializer=energy__pb2.BatchPredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'energy.EnergyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('energy.EnergyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnergyService(object):
    """Service definition for power prediction
    """

    @staticmethod
    def PredictPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy.EnergyService/PredictPower',
            energy__pb2.PredictionRequest.SerializeToString,
            energy__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictPowerBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/energy.EnergyService/PredictPowerBatch',
            energy__pb2.BatchPredictionRequest.SerializeToString,
            energy__pb2.BatchPredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
