kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        enabled:
          - name: Logger
            weight: 1
      postBind:
        enabled:
          - name: Logger